### PR TITLE
Input for owner

### PR DESCRIPTION
**Pull request by vlussenburg**

### CODE REVIEW

**Comment by Andrew5194** [comment]
Few things:

1. We need to rebuild using `make dist-rebuild` right? https://github.com/ForAllSecure/mcode-action#how-to-contribute <-- I would assume after we merge in https://github.com/ForAllSecure/mcode-action/pull/45
2. We should test that this works (I see the comment about adding the integration tests)
3. We should test that the new release works (i.e. `ForAllSecure/mcode-action@<SHA>`)

**Comment by vlussenburg** [comment]
> A few things upon review:
> 
> 1. We need to rebuild using `make dist-rebuild` right? I don't see the related artifacts that get updated after rebuilding, see https://github.com/ForAllSecure/mcode-action#how-to-contribute <-- I would assume after we merge in [Add coverage junit input runid output #45](https://github.com/ForAllSecure/mcode-action/pull/45)
> 2. We should test that this works (I see the comment about adding the integration tests)
> 3. We should test that the new release works (i.e. `ForAllSecure/mcode-action@<SHA>`)

Good point. 1. is done. 2. added a test. 3. need to do

**Comment by vlussenburg** [comment]
> 2. We should test that this works (I see the comment about adding the integration tests)

Works. Verified manually. `--owner vlussenburg` instead of `forallsecure`

**Comment by vlussenburg** [comment]
> 3. We should test that the new release works (i.e. ForAllSecure/mcode-action@<SHA>)

@Andrew5194 I would argue that the integration tests do exactly that and there's no need to do it from an external repo. WDYT?

**Review by unionfindbee — APPROVED** [review]
Looks good!

**Pull request merged**
